service: article-collection

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

package:
  include:
    - dist/**
  exclude:
    - src/**
    - test/**
    - .git/**
    - .gitignore
    - .vscode/**
    - README.md
    - tsconfig.json

functions:
  serverlessTest:
    handler: dist/bin/www/lambda.handler
    events:
      - http: GET articles