service: article-collection

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

package:
  include:
    - src/**
  exclude:
    - test/**
    - .git/**
    - .gitignore
    - README.md

functions:
  serverlessTest:
    handler: src/lambda.handler
    events:
      - http: GET articles